# permissions for end users to view easyservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: easyservice-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: webapp-operator
    app.kubernetes.io/part-of: webapp-operator
    app.kubernetes.io/managed-by: kustomize
  name: easyservice-viewer-role
rules:
- apiGroups:
  - app.kubebuilder.io
  resources:
  - easyservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - app.kubebuilder.io
  resources:
  - easyservices/status
  verbs:
  - get
