---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - app.kubebuilder.io
  resources:
  - easyservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.kubebuilder.io
  resources:
  - easyservices/finalizers
  verbs:
  - update
- apiGroups:
  - app.kubebuilder.io
  resources:
  - easyservices/status
  verbs:
  - get
  - patch
  - update
